#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api:
  prefix: /
  resource: '../src/Controller'

login:
  path:       /login
  controller: App\Controller\SecurityController::login
  methods: POST

logout:
  path:       /logout
  controller: App\Controller\SecurityController::login
  methods: DELETE

get_all_users:
  path: /api/users
  controller: App\Controller\UserController::getAllUsers
  methods:  GET

create_user:
  path: /api/users
  controller: App\Controller\UserController::createUser
  methods:  POST

delete_all_users:
  path: /api/users
  controller: App\Controller\UserController::deleteAllUsers
  methods:  DELETE

get_specific_user:
  path: /api/users/{userID}
  controller: App\Controller\UserController::getSpecificUser
  methods:  GET
  requirements:
    userID: '\d+'

delete_specific_user:
  path: /api/users/{userID}
  controller: App\Controller\UserController::deleteSpecificUser
  methods:  DELETE
  requirements:
    userID: '\d+'

update_specific_user:
  path: /api/users/{userID}
  controller: App\Controller\UserController::updateSpecificUser
  methods:  [PUT, PATCH]
  requirements:
    userID: '\d+'

get_me_user:
  path: /api/users/me
  controller: App\Controller\UserController::getMeUser
  methods:  GET

update_me_user:
  path: /api/users/me
  controller: App\Controller\UserController::updateMeUser
  methods:  PUT, PATCH
